### ISSUE TITLE
awx 1.0.1.231 -- awx-daphne not listening

### ISSUE THREAD

**Issue by worsco** [subuk/awx-rpm#10]
/usr/lib/systemd/system/awx-daphne.service contains:
ExecStart=/opt/awx/bin/daphne -b 127.0.0.1 -p 8051 awx.asgi:channel_layer

Starting awx-daphne.service works, however, the daphne service never binds to 127.0.0.1:8051

lsof -P | grep 8051
..returns nothing.

Need to determine if there is a problem with the start up script or something within daphne not binding to 127.0.0.1:8051

Results is the RESTful Web UI does not update through the websocket

**Comment by subuk** [comment]
You should check system log and `systemctl status awx-daphne` output.

**Comment by worsco** [comment]
● awx-daphne.service - AWX daphne service
   Loaded: loaded (/usr/lib/systemd/system/awx-daphne.service; disabled; vendor preset: disabled)
   Active: active (running) since Tue 2017-11-28 10:31:00 EST; 989ms ago
 Main PID: 29250 (python2)
   Memory: 27.1M
   CGroup: /system.slice/awx-daphne.service
           └─29250 python2 /opt/awx/bin/daphne -b 127.0.0.1 -p 8051 awx.asgi:channel_layer

Nov 28 10:31:00 vcd1mdsbrdk01.corporate.local systemd[1]: Started AWX daphne service.
Nov 28 10:31:00 vcd1mdsbrdk01.corporate.local systemd[1]: Starting AWX daphne service...

It says its running, however nothing is listening on 8051 (I don't know if this is a problem with the systemd start up config or something upstream in awx).

Turns out awx-daphne fails and systemd tries to restart it (still fails).

**Comment by worsco** [comment]
/var/log/messages
Nov 28 10:32:22 vcd1mdsbrdk01 daphne: Traceback (most recent call last):
Nov 28 10:32:22 vcd1mdsbrdk01 daphne: File "/opt/awx/bin/daphne", line 11, in <module>
Nov 28 10:32:22 vcd1mdsbrdk01 daphne: sys.exit(CommandLineInterface.entrypoint())
Nov 28 10:32:22 vcd1mdsbrdk01 daphne: File "/opt/awx/embedded/lib/python2.7/site-packages/daphne/cli.py", line 144, in entrypoint
Nov 28 10:32:22 vcd1mdsbrdk01 daphne: cls().run(sys.argv[1:])
Nov 28 10:32:22 vcd1mdsbrdk01 daphne: File "/opt/awx/embedded/lib/python2.7/site-packages/daphne/cli.py", line 174, in run
Nov 28 10:32:22 vcd1mdsbrdk01 daphne: channel_layer = importlib.import_module(module_path)
Nov 28 10:32:22 vcd1mdsbrdk01 daphne: File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
Nov 28 10:32:22 vcd1mdsbrdk01 daphne: __import__(name)
Nov 28 10:32:22 vcd1mdsbrdk01 daphne: File "/opt/awx/embedded/lib/python2.7/site-packages/awx/asgi.py", line 37, in <module>
Nov 28 10:32:22 vcd1mdsbrdk01 daphne: channel_layer = get_channel_layer()
Nov 28 10:32:22 vcd1mdsbrdk01 daphne: File "/opt/awx/embedded/lib/python2.7/site-packages/channels/asgi.py", line 118, in get_channel_layer
Nov 28 10:32:22 vcd1mdsbrdk01 daphne: return channel_layers[alias].channel_layer
Nov 28 10:32:22 vcd1mdsbrdk01 daphne: File "/opt/awx/embedded/lib/python2.7/site-packages/channels/asgi.py", line 70, in __getitem__
Nov 28 10:32:22 vcd1mdsbrdk01 daphne: self.backends[key] = self.make_backend(key)
Nov 28 10:32:22 vcd1mdsbrdk01 daphne: File "/opt/awx/embedded/lib/python2.7/site-packages/channels/asgi.py", line 33, in make_backend
Nov 28 10:32:22 vcd1mdsbrdk01 daphne: return self._make_backend(name, config)
Nov 28 10:32:22 vcd1mdsbrdk01 daphne: File "/opt/awx/embedded/lib/python2.7/site-packages/channels/asgi.py", line 53, in _make_backend
Nov 28 10:32:22 vcd1mdsbrdk01 daphne: "Cannot import BACKEND %r specified for %s" % (self.configs[name]['BACKEND'], name)
Nov 28 10:32:22 vcd1mdsbrdk01 daphne: channels.asgi.InvalidChannelLayerError: Cannot import BACKEND 'asgi_rabbitmq.RabbitmqChannelLayer' specified for default

**Comment by worsco** [comment]
I wonder if settings.py (settings.py.dist) is out of sync with upstream?  Where is settings.py in the upstream?  If you can point out where settings.py.dist gets populated from, I can compare the Docker edition vs. this RPM edition.

**Comment by worsco** [comment]
CHANNEL_LAYERS = {
    'default': {'BACKEND': 'asgi_amqp.AMQPChannelLayer',
                'ROUTING': 'awx.main.routing.channel_routing',
                'CONFIG': {'url': CELERY_BROKER_URL}}
}

This is from the Docker edition of AWX (/etc/tower/settings.py).  It appears the channel name has changed.

**Comment by worsco** [comment]
I updated /etc/awx/settings.py with the above change, restarted awx-daphne and it now works.  So the settings.py.dist needs to be updated.

systemctl restart awx-daphne
lsof -P | grep 8051
python2   14559            awx    3u     IPv4              45260       0t0        TCP localhost:8051 (LISTEN)

**Comment by subuk** [comment]
Nice, could you make a pull request?

**Comment by MrMEEE** [comment]
This is really old.. and I think it's fixed..

Could you please reopen, if the problem still exists.. 

Builds/installinstructions are located here:
https://github.com/MrMEEE/awx-build/blob/master/installguide.md
