### ISSUE TITLE
Clustering AWX rpm

### ISSUE THREAD

**Issue by ajihandoko** [subuk/awx-rpm#11]
Hi Subuk, I have installed awx rpm and running well in my local environment. I use version 1.0.1.225, and CentOS 7 as a host. A litle question, I have a plan to build cluster (HA Active Passive) with awx rpm using pcs. But I don't know what resource of awx must be added in pcs. Have you tried clustering awx in your local environment ?

**Comment by subuk** [comment]
Hello, I have not tried to setup a cluster for awx yet. It would be great to hear your experience and settings.

**Comment by ajihandoko** [comment]
Oke subuk, please wait I will try in my local environment.

**Comment by tjyang** [comment]
Hi @ajihandoko 

I have some services currently on pcs also.
I just have one  AWX bound to our MS A.D. server successfully.
So I am interested to setup a two nodes AWX using rpm install approach by pacemaker also.
After AWX is clustered, it is ready for production ;)

What  is your progress so far ?

**Comment by MrMEEE** [comment]
Moving this to the builds...
