### ISSUE TITLE
Proxycommand not working

### ISSUE THREAD

**Issue by seniormuffinman** [subuk/awx-rpm#12]
Hi guys,

I'm having issues using proxycommand in this installation. SSH is working if used directly from the server, but I'm not able to modify the ansible.cfg (not present on the machine where the awx.rpm is installed). Is there a way to bypass that and modify the ansible.cfg?

**SSH command with user awx**
$ ssh -i ~/.ssh/awx_rsa USER@SERVER1 uptime
14:45:31 up 12 days, 16:38,  0 users,  load average: 0.00, 0.00, 0.00

**SSH config**
Host SERVER1
        HostName xx.xx.xx.xx
        ServerAliveInterval 60
        TCPKeepAlive yes
        ProxyCommand ssh -q -A USER@JUMPHOST-i /var/lib/awx/.ssh/awx_rsa nc %h %p

**AWX output from web**

SERVER1| UNREACHABLE! => {
    "changed": false, 
    "msg": "Failed to connect to the host via ssh: OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017\r\ndebug1: Reading configuration data /var/lib/awx/.ssh/config\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 53: Applying options for *\r\ndebug1: /etc/ssh/ssh_config line 60: Deprecated option \"useroaming\"\r\ndebug2: resolving \"SERVER1\" port 22\r\nssh: Could not resolve hostname SERVER1: Name or service not known\r\n", 
    "unreachable": true
}

**Comment by MrMEEE** [comment]
Have you built the rpm yourself???

**Comment by seniormuffinman** [comment]
Yes, followed the documentation and built the RPM, then installed the other dependencies and got the product running. But now I'm facing this particular problem. Am I missing anything? Are you able to locate the fiile and change the configurations?

**Comment by MrMEEE** [comment]
Just wanted to check, just know that there is now a repo and a new installation instruction available:
https://github.com/MrMEEE/awx-build/blob/master/installguide

But apart from that have you tried this:

http://docs.ansible.com/ansible-tower/latest/html/administration/tipsandtricks.html#setting-up-a-jump-host-to-use-with-tower

**Comment by seniormuffinman** [comment]
I created the .ssh/config file with all the rules for proxycommand, but I'm wondering if the file is accessed or. The debug mode is showing that the file is being read during the connection, but no rule is applied. The rules are already in use in our functional Ansible server (no AWX).

Tried the configuration in the AWX UI, was off by default. All the documentation I could find was pointing to changing the .cfg file but I cannot find the file to confirm that. I'll keep testing an let you know any updates.

Also, thank you for the updated documentation, looks great!

**Comment by seniormuffinman** [comment]
Adding a few bits from different tests.

UI - Connection debug

```  
Enter passphrase for /tmp/awx_87_KnSBUw/credential_4: 
Identity added: /tmp/awx_87_KnSBUw/credential_4 (/tmp/awx_87_KnSBUw/credential_4)
**No config file found;** using defaults
Loading callback plugin minimal of type stdout, v2.0 from /opt/awx/embedded/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc
META: ran handlers
Using module file /opt/awx/embedded/lib/python2.7/site-packages/ansible/modules/commands/command.py
<SERVER1> ESTABLISH SSH CONNECTION FOR USER: USER
<SERVER1> SSH: EXEC ssh -vvv -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=USER-o ConnectTimeout=10 SERVER1'/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<SERVER1> (255, '', 'OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017\r\ndebug1: **Reading configuration data /var/lib/awx/.ssh/config**\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 53: Applying options for *\r\ndebug1: /etc/ssh/ssh_config line 60: Deprecated option "useroaming"\r\ndebug2: resolving "SERVER1" port 22\r\nssh: **Could not resolve hostname SERVER1: Name or service not known\r\n')**
```

Manual SSH test - awx account

```
$ ssh -q -i ~/.ssh/awx_rsa USER@SERVER1 uptime
 11:11:31 up 17 days, 13:04,  0 users,  load average: 0.04, 0.03, 0.00
```

**Update:**

@MrMEEE I installed the rpm you provided in your repo and followed the instructions. Replicated my configuration from the other installation (users, projects, hosts, keys, etc.) and I'm having the same result. AWX is not checking the config file located in awx's home directory.

**Comment by MrMEEE** [comment]
Hmm... I think you have to use the option in the UI.. 

But you are right... I can't find any documentation either..

But this is not an issue that is related to this project (building AWX as a RPM).. you should raise this to the awx team: https://github.com/ansible/awx/

**Comment by seniormuffinman** [comment]
That's correct, though they provide some kind of workaround if you add an option to the ansible.cfg file. But I cannot find the file, and that might be related to how the rpm approach works. In the containerized approach they seem to have this file in the awx node, but I cannot find it here.

I cannot verify this fixes the problem, but I'll keep trying and let you know. I'll open an issue in the awx project.

Option to be added to ansible.cfg
[ssh_connection]
ssh_args = -F /var/lib/awx/.ssh/config

I'm also having issues with the inventories, again it might not be related to the project itself. Are having issues with the inventories in your installation?

Thanks!

**Comment by MrMEEE** [comment]
Hi

I haven't got any issues with inventories so far... what are you experiencing???

Please return any feedback in regards to the proxy issue.. thanks..

**Comment by seniormuffinman** [comment]
When trying to run a inventory script from a Project (where we store playbooks and dynamic inventories) I'm getting the following error.

I couldn't find any logs so all the testing I'm doing is related to permissions at the time.

```
2018-01-03 15:52:09,413 INFO     awx.main.commands.inventory_import Updating inventory 3: inventory-test-01
2018-01-03 15:52:09,429 INFO     awx.main.commands.inventory_import Reading Ansible inventory source: /var/lib/awx/projects/_6__playbooks/Lifecycle/scripts/decomm-inventory.py
Traceback (most recent call last):
  File "/opt/awx/bin/awx-manage", line 11, in <module>
    sys.exit(manage())
  File "/opt/awx/embedded/lib/python2.7/site-packages/awx/__init__.py", line 109, in manage
    execute_from_command_line(sys.argv)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/awx/embedded/lib64/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/opt/awx/embedded/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 998, in handle
    self.is_custom)
  File "/opt/awx/embedded/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 240, in load_inventory_source
    is_custom=is_custom).load()
  File "/opt/awx/embedded/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 176, in load
    data = self.command_to_json(base_args + ['--list'])
  File "/opt/awx/embedded/lib/python2.7/site-packages/awx/main/management/commands/inventory_import.py", line 153, in command_to_json
    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, env=env)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
```

**Comment by MrMEEE** [comment]
Could you please retry with a newer build, and report any issues here: 

https://github.com/MrMEEE/awx-build/issues
