### ISSUE TITLE
Running a Playbook in AWX Template

### ISSUE THREAD

**Issue by marcalfa1** [subuk/awx-rpm#13]
Is there an upgrade path to upgrade AWX and Ansible for this build to AWX version 1.0.6.3 and Ansible 2.5.  I have a few playbooks that aren't working because the current build is running Ansible 2.3.1.0

https://groups.google.com/forum/#!topic/awx-project/kHVOFVkl-ZI

ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.
The error appears to have been in '/var/lib/awx/projects/_7__test_project/fw_rules_port22.yml': line 5, column 7, but may

be elsewhere in the file depending on the exact syntax problem.

**Comment by MrMEEE** [comment]
Hi... 

Builds are available here:

https://github.com/MrMEEE/awx-build/blob/master/installguide

Repo:

wget -O /etc/yum.repos.d/awx-rpm.repo https://copr.fedorainfracloud.org/coprs/mrmeee/awx-dev/repo/epel-7/mrmeee-awx-dev-epel-7.repo

I switched to Ansible 2.5 a while back...
