### ISSUE TITLE
Can't open '/source/awx-build.spec': No such file or directory at /usr/bin/spectool line 314.

### ISSUE THREAD

**Issue by ghost** [subuk/awx-rpm#14]
-bash-4.2# pwd
/root/awx-standalone/awx/awx-rpm
-bash-4.2# ls -lrt 
total 128
-rw-r--r--. 1 root root  4088 Jun  3 22:21 settings.py.dist
-rw-r--r--. 1 root root  2719 Jun  3 22:21 README.md
-rw-r--r--. 1 root root  2435 Jun  3 22:21 nginx.conf.example
-rwxr-xr-x. 1 root root   742 Jun  3 22:21 build.sh
-rw-r--r--. 1 root root   704 Jun  3 22:21 awx-web.upstart
-rw-r--r--. 1 root root   891 Jun  3 22:21 awx-web.service
-rw-r--r--. 1 root root 32601 Jun  3 22:21 awx.spec
-rw-r--r--. 1 root root   385 Jun  3 22:21 awx-daphne.upstart
-rw-r--r--. 1 root root   529 Jun  3 22:21 awx-daphne.service
-rw-r--r--. 1 root root   390 Jun  3 22:21 awx-channels-worker.upstart
-rw-r--r--. 1 root root   538 Jun  3 22:21 awx-channels-worker.service
-rw-r--r--. 1 root root   470 Jun  3 22:21 awx-celery-worker.upstart
-rw-r--r--. 1 root root   592 Jun  3 22:21 awx-celery-worker.service
-rw-r--r--. 1 root root   403 Jun  3 22:21 awx-celery-beat.upstart
-rw-r--r--. 1 root root   545 Jun  3 22:21 awx-celery-beat.service
-rw-r--r--. 1 root root   369 Jun  3 22:21 awx-cbreceiver.upstart
-rw-r--r--. 1 root root   515 Jun  3 22:21 awx-cbreceiver.service
-rw-r--r--. 1 root root 32607 Jun  3 22:21 awx-build.spec
drwxr-xr-x. 2 root root    81 Jun  3 22:48 buildhelpers
-bash-4.2# sh -x build.sh centos-7
+ set -e
+ mkdir -p /tmp/awx-rpmbuild-cache
++ pwd
+ BUILD_SCRIPT=/root/awx-standalone/awx/awx-rpm/buildhelpers/build.sh
+ case "$1" in
+ DOCKER_IMAGE=ctbuild/centos:7
++ pwd
+ YUM_CONFIG=/root/awx-standalone/awx/awx-rpm/buildhelpers/centos7.yum.conf
+ exec docker run --rm -i -v /home/build/awx-rpm-build/awx-rpm:/source -v /home/build/awx-rpm-build/awx-rpm/result:/result -v /tmp/awx-rpmbuild-cache:/cache -v /root/awx-standalone/awx/awx-rpm/buildhelpers/centos7.yum.conf:/etc/yum.conf -v /root/awx-standalone/awx/awx-rpm/buildhelpers/build.sh:/build.sh ctbuild/centos:7 /build.sh awx-build.spec
+ mkdir -p /source
+ SPECFILE=/source/awx-build.spec
+ yum install -y rpmdevtools yum-utils fakeroot
Loaded plugins: fastestmirror, ovl
Repository base is listed more than once in the configuration
Repository updates is listed more than once in the configuration
Repository extras is listed more than once in the configuration
Loading mirror speeds from cached hostfile
 * base: repos.forethought.net
 * epel: linux.mirrors.es.net
 * extras: linux.mirrors.es.net
 * updates: mirrors.ocf.berkeley.edu
Repository epel is listed more than once in the configuration
Package rpmdevtools-8.3-5.el7.noarch already installed and latest version
Package fakeroot-1.18.4-2.el7.x86_64 already installed and latest version
Resolving Dependencies
--> Running transaction check
---> Package yum-utils.noarch 0:1.1.31-42.el7 will be updated
---> Package yum-utils.noarch 0:1.1.31-45.el7 will be an update
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package            Arch            Version                 Repository     Size
================================================================================
Updating:
 yum-utils          noarch          1.1.31-45.el7           base          119 k

Transaction Summary
================================================================================
Upgrade  1 Package

Total size: 119 k
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Updating   : yum-utils-1.1.31-45.el7.noarch                               1/2 
  Cleanup    : yum-utils-1.1.31-42.el7.noarch                               2/2 
  Verifying  : yum-utils-1.1.31-45.el7.noarch                               1/2 
  Verifying  : yum-utils-1.1.31-42.el7.noarch                               2/2 

Updated:
  yum-utils.noarch 0:1.1.31-45.el7                                              

Complete!
+ useradd -s /bin/bash builder
+ chown builder. /cache -R
+ pushd /source
+ spectool -g /source/awx-build.spec
/source /
Can't open '/source/awx-build.spec': No such file or directory at /usr/bin/spectool line 314.
-bash-4.2# 

Any idea of this issue ?

**Comment by MrMEEE** [comment]
copy awx.spec to awx-build.spec

**Comment by ghost** [comment]
Yes. Copied awx.spec to awx-build.spec .... still the same error ... 

Seems that the error is not from awe-build.spec file or awx.spec file ..it is from the source directory : 

-bash-4.2# cat /etc/redhat-release 
CentOS Linux release 7.4.1708 (Core) 
-bash-4.2# sh -x build.sh centos-7
+ set -e
+ set -x
+ SPECFILE=/source/centos-7
+ yum install -y rpmdevtools yum-utils fakeroot
Loaded plugins: fastestmirror
base                                                                                                                | 3.6 kB  00:00:00     
docker-ee-stable-17.06                                                                                              | 2.9 kB  00:00:00     
epel/x86_64/metalink                                                                                                |  17 kB  00:00:00     
epel                                                                                                                | 3.2 kB  00:00:00     
extras                                                                                                              | 3.4 kB  00:00:00     
updates                                                                                                             | 3.4 kB  00:00:00     
(1/3): epel/x86_64/updateinfo                                                                                       | 932 kB  00:00:00     
(2/3): docker-ee-stable-17.06/x86_64/primary_db                                                                     |  13 kB  00:00:01     
(3/3): epel/x86_64/primary                                                                                          | 3.5 MB  00:00:00     
Loading mirror speeds from cached hostfile
 * base: mirror.hostduplex.com
 * epel: mirror.hmc.edu
 * extras: mirror.hostduplex.com
 * updates: mirror.hostduplex.com
epel                                                                                                                           12585/12585
Package rpmdevtools-8.3-5.el7.noarch already installed and latest version
Package yum-utils-1.1.31-45.el7.noarch already installed and latest version
Package fakeroot-1.18.4-2.el7.x86_64 already installed and latest version
Nothing to do
+ useradd -s /bin/bash builder
useradd: warning: the home directory already exists.
Not copying any file from skel directory into it.
Creating mailbox file: File exists
+ chown builder. /cache -R
+ pushd /source
/source ~/awx-rpm-build/awx-rpm/buildhelpers
+ spectool -g /source/centos-7
Can't open '/source/centos-7': No such file or directory at /usr/bin/spectool line 314.
-bash-4.2#
