### ISSUE TITLE
Building source archive causes 'the input device is not a TTY'

### ISSUE THREAD

**Issue by worsco** [subuk/awx-rpm#4]
`docker run -v `pwd`:/awx --rm -it centos:7 /bin/bash <<EOF
yum install -y epel-release && yum install -y bzip2 gcc-c++ git gettext make python-pip
curl --silent --location https://rpm.nodesource.com/setup_6.x | bash -
yum install -y nodejs
cd /awx/
make sdist
EOF`

The -it causes "the input device is not a TTY".  Changing the switch to '-t' allows it to run.

OS: CentOS 7.4.1708
Docker: docker-ce-17.09.0.ce-1.el7.centos.x86_64

**Comment by subuk** [comment]
Yeah, thanks, I will fix readme soon. Just remove -t flag from docker run command.
```
docker run -v `pwd`:/awx --rm -i centos:7 /bin/bash <<EOF
yum install -y epel-release && yum install -y bzip2 gcc-c++ git gettext make python-pip
curl --silent --location https://rpm.nodesource.com/setup_6.x | bash -
yum install -y nodejs
cd /awx/
make sdist
EOF
```

**Comment by subuk** [comment]
Fixed.

**Comment by worsco** [comment]
Thanks!  Testing out the complete source build process now.  Will provide additional feedback if there are issues ;)
