### ISSUE TITLE
Build Source Code With rpmbuild

### ISSUE THREAD

**Issue by ajihandoko** [subuk/awx-rpm#8]
Hi Subuk, 

I have build with version 1.0.0.505, the build is successfull, but when I install in local environment (centos 7) the service does not go up. 
this is the error from /var/log/messages
`Nov 22 10:25:57 awx awx-manage: conn = _connect(dsn, connection_factory=connection_factory, **kwasync)`
`Nov 22 10:25:57 awx awx-manage: django.db.utils.OperationalError: FATAL:  role "root" does not exist`
`Nov 22 10:25:57 awx systemd: awx-celery-worker.service holdoff time over, scheduling restart.`
what can I do ?

Thanks Subuk

**Comment by subuk** [comment]
Try to pull latest rpm specs and latest awx source dist and rebuild.  This error related to https://github.com/subuk/awx-rpm/commit/8242767fb75d1d6633f374a1369a934a0f0a455b

**Comment by subuk** [comment]
I will close this issue in hope that problem fixed. Feel free to reopen if you have any related questions.
